CREATE TABLE IF NOT EXISTS ator (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nomeator VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS filmes (
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nomefilme VARCHAR(255) NOT NULL,
    idator INT NOT NULL,
    idgenero INT NOT NULL
);
CREATE TABLE IF NOT EXISTS genero (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    descricao VARCHAR(255) NOT NULL
);

ALTER TABLE filmes ADD CONSTRAINT fk_filmes_genero
FOREIGN KEY(idgenero) REFERENCES genero(id);

ALTER TABLE filmes ADD CONSTRAINT fk_filmes_ator
FOREIGN KEY(idator) REFERENCES ator(id);